% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Regression Models - Course Project},
  pdfauthor={Mahadi Sajjad},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Regression Models - Course Project}
\author{Mahadi Sajjad}
\date{2020}

\begin{document}
\maketitle

\hypertarget{executive-summary}{%
\section{Executive summary}\label{executive-summary}}

This paper explores the relationship between miles per US gallon and
type of transmission, using the mtcars dataset in R.

Our analysis showed that manual transmission is better than automatic in
regards to MPG. While accounting for number of cylinders, horsepower and
weight, cars with automatic tranmission have 1.8 higher MPG than those
with manual.

\hypertarget{data-pre-processing}{%
\section{Data pre-processing}\label{data-pre-processing}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_data <-}\StringTok{ }\NormalTok{mtcars}
\KeywordTok{head}\NormalTok{(my_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Transform variables to factors where appropriate}
\NormalTok{my_data}\OperatorTok{$}\NormalTok{cyl <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{cyl)}
\NormalTok{my_data}\OperatorTok{$}\NormalTok{vs <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{vs)}
\NormalTok{my_data}\OperatorTok{$}\NormalTok{am <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{am, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"auto"}\NormalTok{, }\StringTok{"man"}\NormalTok{))}
\NormalTok{my_data}\OperatorTok{$}\NormalTok{gear <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{gear, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"3"}\NormalTok{, }\StringTok{"4"}\NormalTok{, }\StringTok{"5"}\NormalTok{))}
\NormalTok{my_data}\OperatorTok{$}\NormalTok{carb <-}\StringTok{ }\KeywordTok{factor}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{carb)}
\end{Highlighting}
\end{Shaded}

\hypertarget{is-an-automatic-or-manual-transmission-better-for-mpg}{%
\section{1. Is an automatic or manual transmission better for
MPG?}\label{is-an-automatic-or-manual-transmission-better-for-mpg}}

Let's get a first idea about the difference in average MPG between
automatic and manual transmissions:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{aggregate}\NormalTok{(my_data[, }\DecValTok{1}\NormalTok{], }\KeywordTok{list}\NormalTok{(my_data}\OperatorTok{$}\NormalTok{am), mean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Group.1        x
## 1    auto 17.14737
## 2     man 24.39231
\end{verbatim}

There seems to be a clear difference (7.25 MPG) in the average mpg
between automatic and manual transmission (see appendix for plot). Let's
confirm it with a hypothesis test.

H\_0: There is no significant difference in mpg between auto and man
trans.

H\_1: Automatic transmission is associated with lower values of mpg

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(mpg }\OperatorTok{~}\StringTok{ }\NormalTok{am, }\DataTypeTok{data =}\NormalTok{ my_data, }\DataTypeTok{paired =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{alt =} \StringTok{"less"}\NormalTok{)}\OperatorTok{$}\NormalTok{p.value}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.0006868192
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t.test}\NormalTok{(mpg }\OperatorTok{~}\StringTok{ }\NormalTok{am, }\DataTypeTok{data =}\NormalTok{ my_data, }\DataTypeTok{paired =} \OtherTok{FALSE}\NormalTok{, }\DataTypeTok{alt =} \StringTok{"less"}\NormalTok{)}\OperatorTok{$}\NormalTok{estimate}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## mean in group auto  mean in group man 
##           17.14737           24.39231
\end{verbatim}

The p-value is 0.0007 which means that we reject the null at any
reasonable significance level, i.e.~Manual transmission is better for
MPG.

\hypertarget{quantify-the-mpg-difference-between-types-of-transmission.}{%
\section{2. Quantify the MPG difference between types of
transmission.}\label{quantify-the-mpg-difference-between-types-of-transmission.}}

We've fit several linear regression models to quantify the difference in
MPG between automatic and manual type of transmission.

The final model is shown below. The full model selection strategy and
intermediate models can be found in the Appendix.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mdl3 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(mpg }\OperatorTok{~}\StringTok{ }\NormalTok{cyl }\OperatorTok{+}\StringTok{ }\NormalTok{hp }\OperatorTok{+}\StringTok{ }\NormalTok{wt }\OperatorTok{+}\StringTok{ }\NormalTok{am, }\DataTypeTok{data =}\NormalTok{ my_data)}
\KeywordTok{summary}\NormalTok{(mdl3)}\OperatorTok{$}\NormalTok{coef}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                Estimate Std. Error   t value     Pr(>|t|)
## (Intercept) 33.70832390 2.60488618 12.940421 7.733392e-13
## cyl6        -3.03134449 1.40728351 -2.154040 4.068272e-02
## cyl8        -2.16367532 2.28425172 -0.947214 3.522509e-01
## hp          -0.03210943 0.01369257 -2.345025 2.693461e-02
## wt          -2.49682942 0.88558779 -2.819404 9.081408e-03
## amman        1.80921138 1.39630450  1.295714 2.064597e-01
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(mdl3)[}\DecValTok{8}\OperatorTok{:}\DecValTok{9}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $r.squared
## [1] 0.8658799
## 
## $adj.r.squared
## [1] 0.8400875
\end{verbatim}

In addition to the type of transmission, this model takes into account
the number of cylinders, horsepower and weight. The model can explain
87\% of total variance in MPG. While keeping all other variables
constant, MPG increases by 1.8 miles/gallon from automatic to manual
transmission.

\hypertarget{diagnostics}{%
\section{Diagnostics}\label{diagnostics}}

The results of the diagnostic tests are shown below. See Appendix for
plots.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  The residual vs fitted plot does not reveal any non-linear or other
  patterns
\item
  Testing the normality assumption - the qqplot is not a perfect
  straight line but does not appear to be concerning
\item
  There is no evidence of heteroscedasticity from the scale-location
  plot
\item
  All the residuals are within Cook's distance, so there's no reason to
  suspect influential data points in the dataset.
\end{enumerate}

\newpage

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

\#\#1. Boxplot of MPG by type of transmission

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(ggplot2)}
\NormalTok{g <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(my_data, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ am, }\DataTypeTok{y =}\NormalTok{ mpg))}
\NormalTok{g }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_boxplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group =}\NormalTok{ am), }\DataTypeTok{fill =} \StringTok{"olivedrab1"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{xlab}\NormalTok{(}\StringTok{"transmission type"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ylab}\NormalTok{(}\StringTok{"miles/(US) gallon"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Miles/(US) gallon by type of transmission"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CP_files/figure-latex/box-1.pdf}

\#\#2. Diagnostic plots for the final regression model

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{par}\NormalTok{(}\DataTypeTok{mfrow =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\KeywordTok{plot}\NormalTok{(mdl3)}
\end{Highlighting}
\end{Shaded}

\includegraphics{CP_files/figure-latex/diag-1.pdf}

\#\#3. Model selection strategy and intermediate models

\textbf{Model1}

First try a simple linear regression model with MPG as the dependent
variable and transmission type (am) as the independent.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mdl1 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(mpg }\OperatorTok{~}\StringTok{ }\NormalTok{am, }\DataTypeTok{data =}\NormalTok{ my_data)}
\KeywordTok{summary}\NormalTok{(mdl1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = mpg ~ am, data = my_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.3923 -3.0923 -0.2974  3.2439  9.5077 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   17.147      1.125  15.247 1.13e-15 ***
## amman          7.245      1.764   4.106 0.000285 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 4.902 on 30 degrees of freedom
## Multiple R-squared:  0.3598, Adjusted R-squared:  0.3385 
## F-statistic: 16.86 on 1 and 30 DF,  p-value: 0.000285
\end{verbatim}

From the summary we can see that am seems to have a significant effect
on mpg (p-value \textless{} 0.05), and the difference in average MPG
between the two levels of am (manual - auto) is 7.245, which matches the
difference we've already observed. However, am alone does not appear to
be enough to explain the variation in mpg, the R-squared is 0.3598,
which means that this model can only explain 36\% of the total variation
in mpg. We will try to add some more independent variables to the model
from the dataset to try and get a better fit.

Let's have a look at the correlations between mpg and the other
variables in the dataset. We'll try a model that includes variables that
appear to be highly correlated with mpg. Let's pick arbitratily the
variables that have an absolute correlation higher than 0.7 plus the am
variable.

\textbf{Model2}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(mtcars, }\DataTypeTok{method =} \StringTok{"pearson"}\NormalTok{)[, }\StringTok{"mpg"}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        mpg        cyl       disp         hp       drat         wt       qsec 
##  1.0000000 -0.8521620 -0.8475514 -0.7761684  0.6811719 -0.8676594  0.4186840 
##         vs         am       gear       carb 
##  0.6640389  0.5998324  0.4802848 -0.5509251
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mdl2 <-}\StringTok{ }\KeywordTok{lm}\NormalTok{(mpg }\OperatorTok{~}\StringTok{ }\NormalTok{cyl }\OperatorTok{+}\StringTok{ }\NormalTok{disp }\OperatorTok{+}\StringTok{ }\NormalTok{hp }\OperatorTok{+}\StringTok{ }\NormalTok{wt }\OperatorTok{+}\StringTok{ }\NormalTok{am, }\DataTypeTok{data =}\NormalTok{ my_data)}
\KeywordTok{summary}\NormalTok{(mdl2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = mpg ~ cyl + disp + hp + wt + am, data = my_data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.9374 -1.3347 -0.3903  1.1910  5.0757 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 33.864276   2.695416  12.564 2.67e-12 ***
## cyl6        -3.136067   1.469090  -2.135   0.0428 *  
## cyl8        -2.717781   2.898149  -0.938   0.3573    
## disp         0.004088   0.012767   0.320   0.7515    
## hp          -0.032480   0.013983  -2.323   0.0286 *  
## wt          -2.738695   1.175978  -2.329   0.0282 *  
## amman        1.806099   1.421079   1.271   0.2155    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.453 on 25 degrees of freedom
## Multiple R-squared:  0.8664, Adjusted R-squared:  0.8344 
## F-statistic: 27.03 on 6 and 25 DF,  p-value: 8.861e-10
\end{verbatim}

Model 2 explains 87\% of the variance and the adjusted R-squared is
83\%. It is a much better fit than model 1, but includes independent
variables that don't seem to have a significant effect (variables with
p-value higher than 0.05). Transmission type doesn't seem to be
significant in this model either. Let's try to remove variable ``disp''.

\end{document}
